# Generated by Django 6.1.1 on 2026-09-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection 1')
            """, """
            DELETE FROM store_collection WHERE title = 'collection 1'
            """)
    ]